version: '3.8'
services: 
  db:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432
  app:
    build: backend/.
    environment:
      - SECRET_KEY=325vnshi4325fsdiot
      - DB_LINK=postgresql://postgres:postgres@db:5432
    depends_on: 
      - db
    ports:
      - 5000:5000